version: "3.7"
services:
  api:
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./.production.env:/usr/app/.env"
    environment:
      NODE_ENV: 'production'
