export enum EMainEvents {
    CLOSE_SESSION = 'CLOSE_SESSION',
    REGISTER_USER = 'REGISTER_USER',
    PLAYERS_ONLINE = 'PLAYERS_ONLINE',
    JOIN_ADMIN_ROOM = 'JOIN_ADMIN_ROOM',
    WIN_EVENT = 'WIN_EVENT',
    NOTIFICATION = 'NOTIFICATION',
    SOMEONE_WIN = 'SOMEONE_WIN', // Only send
}
